project:
  type: website
  output-dir: docs

website:
  title: "quarto-forwardlash-reprex"
  site-url: https://graphdr.github.io/quarto-forwardslash-reprex
  description: |
    A reprex for the forwardslash in image links 
    in the XML file.
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



